export const SHOW_DAILY_DATA = 'SHOW_DAILY_DATA';
export const ADD_FETCHED_DATA = 'ADD_FETCHED_DATA';
export const ADD_HISTORICAL_DATA = 'ADD_HISTORICAL_DATA';
export const ADD_STATE_DATA = 'ADD_STATE_DATA';
export const ADD_VACCINE_DATA = 'ADD_VACCINE_DATA';
